import '../scss/style.scss';
console.log('Works!');
import {inicializeSwiper} from '../js/slider.js';
inicializeSwiper();
import {callbackClickHandler} from "./callbackscript";
callbackClickHandler();
import {feedbackClickHandler} from "./feedbackscript";
feedbackClickHandler();
import {burgerClickHandler} from "./burgerscript";
burgerClickHandler();
import {priceSwiperHandler} from "./priceSwiperHandler";
priceSwiperHandler();
import {repairSwiperHandler} from "./repairSwiperHandler";
repairSwiperHandler();
import {linkReadHandler} from "./mainBlockButtonHandler";
linkReadHandler();
